name: diet_scan_ia
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.0+2
  google_generative_ai: ^0.4.6
  flutter_bloc: ^8.1.6
  file_picker: ^8.1.2
  path_provider: ^2.1.4
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true